# Generated by Django 5.2.14 on 2026-05-23 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Назва товару')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Залишок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Товар складу',
                'verbose_name_plural': 'Склад',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Кличка')),
                ('species', models.CharField(max_length=100, verbose_name='Вид тварини')),
                ('breed', models.CharField(blank=True, max_length=120, verbose_name='Порода')),
                ('sex', models.CharField(choices=[('unknown', 'Не вказано'), ('male', 'Самець'), ('female', 'Самка')], default='unknown', max_length=20, verbose_name='Стать')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('age_text', models.CharField(blank=True, max_length=80, verbose_name='Вік')),
                ('features', models.TextField(blank=True, verbose_name='Особливості')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('owner_full_name', models.CharField(max_length=160, verbose_name='ПІБ власника')),
                ('owner_phone', models.CharField(max_length=40, verbose_name='Телефон власника')),
                ('owner_comment', models.TextField(blank=True, verbose_name='Коментар власника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Пацієнт',
                'verbose_name_plural': 'Пацієнти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=160, verbose_name='Назва вакцини')),
                ('vaccination_date', models.DateField(verbose_name='Дата вакцинації')),
                ('next_vaccination_date', models.DateField(verbose_name='Дата наступної вакцинації')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='clinic.patient', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Вакцинація',
                'verbose_name_plural': 'Вакцинації',
                'ordering': ['next_vaccination_date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата прийому')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('treatment', models.TextField(blank=True, verbose_name='Лікування / призначення')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinic.patient', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Прийом',
                'verbose_name_plural': 'Прийоми',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
